default_platform(:ios)

platform :ios do

  desc "Create App Identifier if not already in App Store Connect"
  lane :create_app_identifier_and_add_app_to_connect do
    begin
      produce(
        app_identifier: ENV['APP_IDENTIFIER'],  
        app_name: ENV['APP_NAME'],  
        sku: ENV['APP_SKU'],        
        platform: "ios",           
        language: "en-US",
        team_id: ENV['APPLE_TEAM_ID'],
        username: ENV['FASTLANE_USER'],
        skip_itc: false, 
        skip_devcenter: false
      )
      UI.success("App Identifier successfully created and added to App Store Connect!")
    rescue => e
      UI.message("App might already exist. Skipping creation. Error: #{e.message}")
    end
  end

  #desc "Get App ID"
  # lane :get_app_id do
  #   Spaceship::Tunes.login(username: ENV['FASTLANE_USER'])
  #   app = Spaceship::Tunes::Application.find("com.yourcompany.yourappname") # Your bundle ID
  #   UI.message("App Store Connect App ID: #{app.apple_id}")
  # end
  

  desc "Submit to App Store"
  lane :submit_to_app_store do
    sh("npx eas submit -p ios --profile production --latest")
  end

  desc "Build and Submit App using EAS and Fastlane"
  lane :deploy do
    UI.message("Starting the deployment process...")
    create_app_identifier_and_add_app_to_connect
    # sync_certificates_and_profiles
    sh("npx eas build -p ios --profile production --auto-submit")
    submit_to_app_store
    UI.success("App successfully submitted to the App Store!")
  end
end
