before_all do
    ensure_git_branch
    ensure_git_staus_clean
    git pull
end

platform :ios do
    private_lane : stageing_build do
    increment_build_number_in_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj')
    end
end